__include__: [
  '../dataset/buspassenger_detection.yml',
  '../runtime.yml',
  './include/dataloader_buspassenger.yml',
  './include/optimizer.yml',
  './include/daear_detr_r50vd_buspassenger_dualencode.yml',
]
log_step: 1
epoches: 12
checkpoint_step: 2
output_dir: ../models_trained/object_detection/daear_detr/buspassenger/rtdetr_dualencode_r50vd_1x_buspassenger_random/202303181435
