__include__: [
  '../dataset/buspassenger_vrs_detection.yml',
  '../runtime.yml',
  './include/dataloader_buspassenger_vrs.yml',
  './include/optimizer.yml',
  './include/daear_detr_r50vd_buspassenger_vrs_dualencode_level4_encodestage2_residual_AttentionGated.yml',
]
log_step: 100
epoches: 72
checkpoint_step: 1
output_dir: ../models_trained/object_detection/daear_detr/buspassenger_new/daear_detr_dualencode_level4_encodestage2_residual_AttentionGated_r50vd_6x_buspassenger_new/LoadPretrainedModelAndFrozenLayers_Augment/
