__include__: [
  '../dataset/buspassenger_detection.yml',
  '../runtime.yml',
  './include/dataloader_buspassenger.yml',
  './include/optimizer.yml',
  './include/daear_detr_r50vd_buspassenger.yml',
]
log_step: 100
epoches: 72
checkpoint_step: 1
output_dir: ../models_trained/object_detection/daear_detr/buspassenger/daear_detr_r50vd_6x_buspassenger_random/202303211023
